# 动态配置，每个套餐都起一个  service!!
services:
- name: service-30002
  addr: :30002
  observer: observeService # handler 上的观测器
  handler:
    type: http
    auther: auther-0
    limiter: limiter-0
    observer: observeUser # handler 上的观测器
    metadata:
      limiter.refreshInterval: 30s
      enableStats: true # 开启统计
      observePeriod: 5s
  listener:
    type: tls
  metadata:
    knock: www.google.com
    probeResist: file:/var/www/html/index.html
    enableStats: true # 开启统计
    observePeriod: 5s

tls:
  certFile: /etc/gost/fullchain.pem
  keyFile: /etc/gost/privkey.pem

# 固定值，接口观测
observers:
- name: observeUser
  plugin:
    type: http
    addr: http://127.0.0.1:30000/plugin/observeUser
    timeout: 10s
- name: observeService
  plugin:
    type: http
    addr: http://127.0.0.1:30000/plugin/observeService
    timeout: 10s

# 固定值，接口观测
authers:
- name: auther-0
  plugin:
    type: http
    addr: http://127.0.0.1:30000/plugin/auther

# 固定值，接口观测
limiters:
- name: limiter-0
  plugin:
    type: http
    addr: http://127.0.0.1:30000/plugin/limiter

api:
  addr: 0.0.0.0:30001
  pathPrefix: /api
  accesslog: true
  auth:
    username: admin
    password: adminadmin
